### PR TITLE
resample v2

### PR DESCRIPTION
**Pull request by buthanoid**

### CODE REVIEW

**Comment by bourgesl** [comment]
Please have a look at my changes to skip useless computation tasks ... and also make the new 'Modify Image' dialog more user-friendly (formatter, layout, labels)
Modify image_199

**Comment by buthanoid** [comment]
Changed `GridLayout` to `GridBagLayout` and renamed some labels.
I did not rounded the values because the simple rounding can modify "image width in pixel" computed value so I thought it was complicating

**Comment by bourgesl** [comment]
Please use:
FOV (mas)
Increments (mas)
Image size
And use a number formatter (3 digits max)

**Comment by buthanoid** [comment]
Updated but I think it is imperfect because the rounding slightly modifies FOV and PixelSize, which can be enough to compute an image size different from the initial one (just opening the dialog already propose a different image size).
I try to investigate more on the issue

After investigation.
*Before the rounding*:
- image FOV = 20.000000484287998, image inc = 0.6250000151339999, image size = 32
- (viewport does not change the values)
- `newSize = (int) Math.ceil(imageSize * (inc / newInc)); `  = 32.0

*After the rounding*: 
- image FOV = 20.000000484287998, image inc = 0.6250000151339999, image size = 32
- rounded FOV = 20.0, rounded Inc = 0.625
- (viewport does not change the values)
- `newSize = (int) Math.ceil(imageSize * (inc / newInc)); `  = 32.000000774860794 = 33.0

So by a little difference 32 became 33 and will become 34 eventually.

**Comment by bourgesl** [comment]
You're right, the computeNewNbPixels() method should handle numerical precision issue:
I propose to consider increment changed if abs(newInc - inc) > 1e-3 mas :

```
public static int computeNewNbPixels(final int nbPixels, final double inc, final double newInc) {
        if (Math.abs(newInc - inc) < 1e-3) {
            return nbPixels;
        }
        int newSize = (int) Math.ceil(nbPixels * (inc / newInc));

        // check bounds:
        newSize = checkBounds(newSize, 1, MAX_IMAGE_SIZE);

        // Keep it square and even to avoid any black border (not present originally):
        return (newSize % 2 != 0) ? newSize + 1 : newSize;
    }
```
Moreover, it is a bit surprising that increasing Fov by 0.001 for image size = 64 => make nb pixel incremented, then made even => +2 pixels = 66 ! (but it is correct)

**Comment by bourgesl** [comment]
Anyway could you fix the form (resizing issue) when typing in fields ... probably adjust columnSize , formatter to always display 3 digits and fix adjusted label (size)

**Comment by bourgesl** [comment]
Looks good, go !

**Pull request merged**
